version: "3.9"

services:
  schedule-db:
    container_name: schedule-db
    image: postgres:14.7
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - config/common.env
    volumes:
      - ./config:/app/config
      - ./config:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "512M"
        reservations:
          cpus: "0.2"
          memory: "256M"
  
  api-service:
    container_name: api-service
    build: API
    depends_on:
      - schedule-db
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    ports:
      - "7013:80"
    env_file:
      - config/common.env

  getting-service:
    container_name: getting-service
    build: getting-service
    depends_on:
      - schedule-db
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    ports:
      - "5723:5723"
    env_file:
      - config/common.env
      - config/telegram.env
    volumes:
      - ./config:/app/config
      